name: Update README from Issue
on:
    issues:
        # TODO: remove reopened trigger
        types: [opened, reopened]

jobs:
    process-issue:
        if: contains(github.event.issue.labels.*.name, 'New Position')
        runs-on: ubuntu-latest
        env:
            ISSUE_NUMBER: ${{ github.event.issue.number }}
            BRANCH_NAME: new-position-"$ISSUE_NUMBER"
            AUTHOR: ${{ github.event.issue.user.login }}
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        permissions:
            issues: write
            contents: write
            pull-requests: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Assign Issue to Author
              uses: pozil/auto-assign-issue@v1
              with:
                  assignees: "$AUTHOR"
            - name: Edit README
              env:
                  ISSUE_CONTENT: ${{ toJson(github.event.issue) }}
              run: |
                  git checkout -b "$BRANCH_NAME"
                  git config user.email "action@github.com"
                  git config user.name "GitHub Action"
                  python3 .github/workflows/edit_readme.py
                  git add README.md
                  git commit -m "New positions added by $AUTHOR in issue #$ISSUE_NUMBER."
                  git push -u origin HEAD
            - name: Pull Request
              # TODO: add --reviewer flag to request review from education committee team
              run: gh pr create --assignee "$AUTHOR" --base main --fill --body "Reference issue ($ISSUE_NUMBER)" --label "New Position"
            - name: Thank-you Message
              run: gh issue comment "$ISSUE_NUMBER" --body "$MESSAGE"
              env:
                  MESSAGE: Thank you for submitting a new position! Our maintainers will review your PR soon.
            - name: Close issue
              run: gh issue close "$ISSUE_NUMBER"
