name: Update README from Issue
on:
    issues:
        # TODO: remove reopened trigger
        types: [opened, reopened]

jobs:
    process-issue:
        if: contains(github.event.issue.labels.*.name, 'New Position')
        runs-on: ubuntu-latest
        env:
            ISSUE_NUMBER: ${{ github.event.issue.number }}
            AUTHOR: ${{ github.event.issue.user.login }}
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        permissions:
            issues: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Assign Issue to Author
              uses: pozil/auto-assign-issue@v1
              with:
                  assignees: "$AUTHOR"
            - name: Edit README
              env:
                  ISSUE_CONTENT: ${{ toJson(github.event.issue) }}
              run: |
                  git checkout -b new-position-"$ISSUE_NUMBER"
                  python3 .github/workflows/edit_readme.py
                  git add README.md
                  git commit -m "New positions added by $AUTHOR in issue #$ISSUE_NUMBER."
                  git push -u origin HEAD
            - name: Thank-you Message
              run: gh issue comment "$ISSUE_NUMBER" --body "$MESSAGE"
              env:
                  MESSAGE: Thank you for submitting new position(s)! Our maintainers will review your PR soon.
            - name: Close issue
              run: gh issue close "$ISSUE_NUMBER"
